# Generated by Django 3.1.2 on 2024-05-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240526_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraitem',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.producto'),
        ),
    ]
