# Generated by Django 3.1.2 on 2024-05-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240526_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total',
        ),
    ]
